// ─────────────────────────────────────────────────────────
//  airlineLogoService
//  Maps an ICAO / IATA / airline-name hint → a canonical
//  IATA two-letter code and a CDN logo URL.
//
//  URL template: https://pics.avs.io/{w}/{h}/{IATA}.png
//    • free, no API key, HTTPS + CORS
//    • returns a transparent PNG sized on demand
//    • 404s for unknown codes (we treat that as "fallback")
//
//  Consumers (AirportSidebar, Sidebar, InsightsPanel) pass the
//  callsign (e.g. "BAW123") and airline name they already have;
//  we derive the IATA code without extra network calls.
//
//  When no IATA match is found, `logoUrl` is null and callers
//  render the existing letter-badge fallback.
// ─────────────────────────────────────────────────────────

// ICAO (3 letter) → IATA (2 letter). Covers the major operators
// present in openSkyService.js ICAO_AIRLINES list and a handful
// of extras commonly seen on ADS-B feeds. Left-side is the 3-letter
// operator prefix used in callsigns like "BAW456" → "BAW" → "BA".
const ICAO_TO_IATA = {
  AAL: 'AA', AAR: 'OZ', ACA: 'AC', AFR: 'AF',
  AIC: 'AI', ANA: 'NH', ANZ: 'NZ', ARG: 'AR',
  ASA: 'AS', AUA: 'OS', AVA: 'AV', AXM: 'AK',
  AZA: 'AZ', AZU: 'AD', BAW: 'BA', BEL: 'SN',
  BTI: 'BT', CAL: 'CI', CCA: 'CA', CES: 'MU',
  CPA: 'CX', CSN: 'CZ', CTN: 'OU', DAL: 'DL',
  DLH: 'LH', EIN: 'EI', ELY: 'LY', ETD: 'EY',
  ETH: 'ET', EZY: 'U2', FDB: 'FZ', FIN: 'AY',
  GEC: 'LH', GFA: 'GF', GTI: '5Y', HAL: 'HA',
  HVN: 'VN', IBE: 'IB', IBS: 'I2', ICE: 'FI',
  ISS: 'IG', JAI: '6E', JAL: 'JL', JBU: 'B6',
  JNA: 'LJ', KAL: 'KE', KAC: 'KU', KLM: 'KL',
  LAN: 'LA', LOT: 'LO', MAS: 'MH', MEA: 'ME',
  MSR: 'MS', NAX: 'DY', NKS: 'NK', OAL: 'OA',
  PIA: 'PK', QFA: 'QF', QTR: 'QR', RAM: 'AT',
  RJA: 'RJ', RYR: 'FR', SAS: 'SK', SIA: 'SQ',
  SKW: 'OO', SVA: 'SV', SWR: 'LX', TAM: 'JJ',
  TAP: 'TP', THA: 'TG', THY: 'TK', TOM: 'BY',
  UAE: 'EK', UAL: 'UA', UPS: '5X', VIR: 'VS',
  VOE: 'V7', VRD: 'VX', WJA: 'WS', WZZ: 'W6',
};

// Two-letter IATA prefix fallback (used when the callsign starts
// with an IATA rather than ICAO code, e.g. "BA123"). Rare on ADS-B
// but common in scheduled items generated by airportService.
const IATA_PREFIXES = new Set(Object.values(ICAO_TO_IATA));

// Airline-name hint → IATA. Used only when we couldn't resolve
// the callsign. Helps keep scheduled fallback rows consistent.
const NAME_TO_IATA = {
  'American Airlines': 'AA', 'Air Canada': 'AC', 'Air France': 'AF',
  'Air India': 'AI', 'All Nippon Airways': 'NH', 'Alaska Airlines': 'AS',
  'Austrian Airlines': 'OS', 'British Airways': 'BA', 'Brussels Airlines': 'SN',
  'Cathay Pacific': 'CX', 'China Airlines': 'CI', 'China Eastern': 'MU',
  'China Southern': 'CZ', 'Delta Air Lines': 'DL', 'easyJet': 'U2',
  'Emirates': 'EK', 'Etihad Airways': 'EY', 'Finnair': 'AY',
  'Iberia': 'IB', 'Japan Airlines': 'JL', 'JetBlue': 'B6',
  'KLM': 'KL', 'Korean Air': 'KE', 'LATAM Airlines': 'LA',
  'Lufthansa': 'LH', 'Qantas': 'QF', 'Qatar Airways': 'QR',
  'Ryanair': 'FR', 'Singapore Airlines': 'SQ', 'Southwest Airlines': 'WN',
  'Spirit Airlines': 'NK', 'Swiss': 'LX', 'TAP Air Portugal': 'TP',
  'Thai Airways': 'TG', 'Turkish Airlines': 'TK', 'United Airlines': 'UA',
  'Virgin Atlantic': 'VS', 'Wizz Air': 'W6', 'Aer Lingus': 'EI',
  'Ryanair UK': 'RK', 'TUI Airways': 'BY', 'SkyWest Airlines': 'OO',
  'Scandinavian Airlines': 'SK', 'Norwegian': 'DY', 'Saudia': 'SV',
  'Vietnam Airlines': 'VN', 'Pakistan International': 'PK',
  'Malaysia Airlines': 'MH', 'flydubai': 'FZ',
};

function normaliseCallsign(value) {
  return String(value ?? '').trim().toUpperCase().replace(/\s+/g, '');
}

/**
 * Derive a best-effort IATA code from a callsign / airline name.
 * Returns null when no match is found.
 */
export function resolveAirlineIata(callsign, airlineName) {
  const cs = normaliseCallsign(callsign);
  if (cs.length >= 3) {
    const hit = ICAO_TO_IATA[cs.slice(0, 3)];
    if (hit) return hit;
  }
  if (cs.length >= 2 && IATA_PREFIXES.has(cs.slice(0, 2))) {
    return cs.slice(0, 2);
  }
  if (airlineName && NAME_TO_IATA[airlineName]) return NAME_TO_IATA[airlineName];
  return null;
}

/**
 * Build a logo URL for the resolved IATA code. Width/height in px.
 * Uses the pics.avs.io CDN (serves transparent PNGs, CORS-enabled).
 */
export function airlineLogoUrl(iata, w = 120, h = 40) {
  if (!iata) return null;
  return `https://pics.avs.io/${w}/${h}/${iata}.png`;
}

/**
 * Convenience helper — returns `{ iata, logoUrl, initials, hue }`.
 *   • `initials` + `hue` drive the letter-badge fallback (same visual
 *     language Sidebar.jsx already uses).
 *   • Callers can render <img> if `logoUrl` is non-null and attach an
 *     onError that swaps in the badge markup.
 */
export function getAirlineBrand(callsign, airlineName, size = { w: 120, h: 40 }) {
  const iata = resolveAirlineIata(callsign, airlineName);
  const name = airlineName && airlineName !== 'Unknown' ? airlineName : (iata ?? 'Airline');
  const initials = name.split(/\s+/).slice(0, 2).map((w) => w[0] ?? '').join('').toUpperCase() || '✈';
  const hue = [...name].reduce((h, c) => (h * 31 + c.charCodeAt(0)) % 360, 0);
  return {
    iata,
    logoUrl: airlineLogoUrl(iata, size.w, size.h),
    initials,
    hue,
  };
}
